export const NOTES_RECEIVED = "NOTES_RECEIVED";
export const NOTE_RECEIVED = "NOTE_RECEIVED";
export const TOGGLE_ADD = "TOGGLE_ADD";
export const SEARCH_NOTES = "SEARCH_NOTES";
export const FILTER_RECEIVED = "FILTER_RECEIVED";
