# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# notes = Note.create([ { content: "If not now, when?  If not me, who?", color: "blue" },
#               { content: "Trump values do not live in California", color: "pink" },
#               { content: "I <3 you", color: "yellow" },
#               { content: "Make America human again", color: "yellow" } ])
#
# tags = Tag.create([ { name: "transgender", note_id: 1, occurrences: 1 },
#              { name: "love", note_id: 0, occurrences: 3 },
#              { name: "patriotism", note_id: 1, occurrences: 2 }])
#
# NoteTag.create([ { note_id: notes[0].id, tag_id: tags[1].id },
#                   { note_id: notes[1].id, tag_id: tags[1].id }])
randGenerator = Random.new
colorHash = { 0 => "yellow", 1 => "blue", 2 => "pink", 3 => "orange", 4 => "green" }
note1 = Note.create( { content: "If not now, when? If not me, who?", color: colorHash[randGenerator.rand(0..4)]})
note2 = Note.create( { content: "Black Lives Matter", color: colorHash[randGenerator.rand(0..4)]})
note3 = Note.create( { content: "In solidarity with my undocumented immigrant brothers, sisters, and friends", color: colorHash[randGenerator.rand(0..4)]})
note4 = Note.create( { content: "I don't know you but I will fight for you", color: colorHash[randGenerator.rand(0..4)]})
note5 = Note.create( { content: "May I continue to treat everyone with kindness", color: colorHash[randGenerator.rand(0..4)]})
note6 = Note.create( { content: "You are here to stay", color: colorHash[randGenerator.rand(0..4)]})
note7 = Note.create( { content: "America is in this together", color: colorHash[randGenerator.rand(0..4)]})
note8 = Note.create( { content: "Solidarity forever", color: colorHash[randGenerator.rand(0..4)]})
note9 = Note.create( { content: "Remember! You are not alone", color: colorHash[randGenerator.rand(0..4)]})
note10 = Note.create( { content: "<3 <3 Love love love <3 <3", color: colorHash[randGenerator.rand(0..4)]})
note11 = Note.create( { content: "We got your back!", color: colorHash[randGenerator.rand(0..4)]})
note12 = Note.create( { content: "We won't turn away, pretend it's okay. We will stand up and fight when needed!", color: colorHash[randGenerator.rand(0..4)]})
note13 = Note.create( { content: "Lick wounds. Make plan. Rise up.", color: colorHash[randGenerator.rand(0..4)]})
note14 = Note.create( { content: "Trump values do not live in California", color: colorHash[randGenerator.rand(0..4)]})
note15 = Note.create( { content: "I am almost done mourning. Soon, we rise.", color: colorHash[randGenerator.rand(0..4)]})
note16 = Note.create( { content: "Universe, thank you that today, I have everything I need.", color: colorHash[randGenerator.rand(0..4)]})
note17 = Note.create( { content: "Let this be the end of the divisiveness", color: colorHash[randGenerator.rand(0..4)]})
note18 = Note.create( { content: "Keep fighting to make your dreams a reality", color: colorHash[randGenerator.rand(0..4)]})
note19 = Note.create( { content: "Thank you for being", color: colorHash[randGenerator.rand(0..4)]})
note20 = Note.create( { content: "Fight against bigotry", color: colorHash[randGenerator.rand(0..4)]})
note21 = Note.create( { content: "No more white ally silence. Do something.", color: colorHash[randGenerator.rand(0..4)]})
note22 = Note.create( { content: "Tomorrow is another day to fight for love", color: colorHash[randGenerator.rand(0..4)]})
note23 = Note.create( { content: "I regret not saying or doing more. Sending <3 to you and Grandma.", color: colorHash[randGenerator.rand(0..4)]})
note24 = Note.create( { content: "Transgender people: you are not alone", color: colorHash[randGenerator.rand(0..4)]})
note25 = Note.create( { content: "Let's talk without forgetting to listen", color: colorHash[randGenerator.rand(0..4)]})
note26 = Note.create( { content: "The day the world ended is the same day it began. We took the pain and tattered reins and towards teh light we ran.", color: colorHash[randGenerator.rand(0..4)]})
note27 = Note.create( { content: "Make America love again", color: colorHash[randGenerator.rand(0..4)]})
note28 = Note.create( { content: "Still with her", color: colorHash[randGenerator.rand(0..4)]})
note29 = Note.create( { content: "Latinos still with her", color: colorHash[randGenerator.rand(0..4)]})
note30 = Note.create( { content: "Let's give him a chance", color: colorHash[randGenerator.rand(0..4)]})
note31 = Note.create( { content: "Now is the time for solidarity, action, empathy", color: colorHash[randGenerator.rand(0..4)]})
note32 = Note.create( { content: "Take this moment and turn it into positive action", color: colorHash[randGenerator.rand(0..4)]})
note33 = Note.create( { content: "Trans lives matter", color: colorHash[randGenerator.rand(0..4)]})
note34 = Note.create( { content: "We will not break. Stay strong.", color: colorHash[randGenerator.rand(0..4)]})
note35 = Note.create( { content: "Love wins! We'll get through this together.", color: colorHash[randGenerator.rand(0..4)]})
note36 = Note.create( { content: "I don't need to know you to love you. Allow peace, kindness, and respect to live in your heart.", color: colorHash[randGenerator.rand(0..4)]})
note37 = Note.create( { content: "I'll miss you, Martin.", color: colorHash[randGenerator.rand(0..4)]})
note38 = Note.create( { content: "You can be an agent of change", color: colorHash[randGenerator.rand(0..4)]})
note39 = Note.create( { content: "Empathy means not taking the easy way out", color: colorHash[randGenerator.rand(0..4)]})

solidarity = Tag.create( { name: "solidarity", occurrences: 12 })
hereToStay = Tag.create({ name: "hereToStay", occurrences: 7 })
blm = Tag.create({ name: "blackLivesMatter", occurrences: 5 })
tlm = Tag.create( { name: "transLivesMatter", occurrences: 5 })
resist = Tag.create( { name: "resist", occurrences: 10 })
imWithHer = Tag.create( { name: "ImWithHer", occurrences: 4 })
love = Tag.create({ name: "love", occurrences: 8 })
gratitude = Tag.create( { name: "gratitude", occurrences: 4 })
humanKindness = Tag.create({ name: "humanKindness", occurrences: 9 })
undocumented = Tag.create({ name: "undocumented", occurrences: 4 })
nastyWomen = Tag.create({ name: "nastyWomen", occurrences: 2 })
martin = Tag.create({name: "martin", occurrences: 1})
brownlm = Tag.create( { name: "brownLivesMatter", occurrences: 5 })

NoteTag.create( { note_id: note34.id, tag_id: undocumented.id })
NoteTag.create( { note_id: note29.id, tag_id: undocumented.id })
NoteTag.create( { note_id: note21.id, tag_id: undocumented.id })
NoteTag.create( { note_id: note18.id, tag_id: undocumented.id })
NoteTag.create( { note_id: note1.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note1.id, tag_id: resist.id })
NoteTag.create( { note_id: note2.id, tag_id: blm.id })
NoteTag.create( { note_id: note3.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note3.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note3.id, tag_id: resist.id })
NoteTag.create( { note_id: note4.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note4.id, tag_id: resist.id })
NoteTag.create( { note_id: note5.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note5.id, tag_id: love.id })
NoteTag.create( { note_id: note6.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note7.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note7.id, tag_id: blm.id })
NoteTag.create( { note_id: note7.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note7.id, tag_id: tlm.id })
NoteTag.create( { note_id: note7.id, tag_id: brownlm.id })
NoteTag.create( { note_id: note8.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note8.id, tag_id: resist.id })
NoteTag.create( { note_id: note9.id, tag_id: love.id })
NoteTag.create( { note_id: note9.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note9.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note10.id, tag_id: love.id })
NoteTag.create( { note_id: note10.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note11.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note11.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note12.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note12.id, tag_id: resist.id })
NoteTag.create( { note_id: note12.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note13.id, tag_id: imWithHer.id })
NoteTag.create( { note_id: note13.id, tag_id: resist.id })
NoteTag.create( { note_id: note13.id, tag_id: nastyWomen.id })
NoteTag.create( { note_id: note14.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note14.id, tag_id: brownlm.id })
NoteTag.create( { note_id: note14.id, tag_id: imWithHer.id })
NoteTag.create( { note_id: note14.id, tag_id: blm.id })
NoteTag.create( { note_id: note15.id, tag_id: resist.id })
NoteTag.create( { note_id: note16.id, tag_id: gratitude.id })
NoteTag.create( { note_id: note17.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note17.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note19.id, tag_id: gratitude.id })
NoteTag.create( { note_id: note19.id, tag_id: tlm.id })
NoteTag.create( { note_id: note20.id, tag_id: brownlm.id })
NoteTag.create( { note_id: note20.id, tag_id: blm.id })
NoteTag.create( { note_id: note20.id, tag_id: tlm.id })
NoteTag.create( { note_id: note20.id, tag_id: resist.id })
NoteTag.create( { note_id: note21.id, tag_id: brownlm.id })
NoteTag.create( { note_id: note21.id, tag_id: blm.id })
NoteTag.create( { note_id: note21.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note22.id, tag_id: love.id })
NoteTag.create( { note_id: note22.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note23.id, tag_id: gratitude.id })
NoteTag.create( { note_id: note24.id, tag_id: tlm.id })
NoteTag.create( { note_id: note27.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note27.id, tag_id: love.id })
NoteTag.create( { note_id: note28.id, tag_id: imWithHer.id })
NoteTag.create( { note_id: note28.id, tag_id: nastyWomen.id })
NoteTag.create( { note_id: note29.id, tag_id: imWithHer.id })
NoteTag.create( { note_id: note29.id, tag_id: brownlm.id })
NoteTag.create( { note_id: note29.id, tag_id: hereToStay.id })
NoteTag.create( { note_id: note31.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note31.id, tag_id: love.id })
NoteTag.create( { note_id: note33.id, tag_id: tlm.id })
NoteTag.create( { note_id: note34.id, tag_id: resist.id })
NoteTag.create( { note_id: note34.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note35.id, tag_id: love.id })
NoteTag.create( { note_id: note35.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note35.id, tag_id: solidarity.id })
NoteTag.create( { note_id: note36.id, tag_id: love.id })
NoteTag.create( { note_id: note36.id, tag_id: humanKindness.id })
NoteTag.create( { note_id: note37.id, tag_id: martin.id })
NoteTag.create( { note_id: note37.id, tag_id: gratitude.id })
NoteTag.create( { note_id: note38.id, tag_id: resist.id })

listenHarder = Tag.create( { name: "listenHarder", occurrences: 2 })
riseUp = Tag.create( { name: "riseUp", occurrences: 9 })

[note39, note38, note34, note32, note31, note20, note15, note13, note1].each do |note|
  NoteTag.create( { note_id: note.id, tag_id: riseUp.id })
end

[note5, note17, note25, note39].each do |note|
  NoteTag.create( { note_id: note.id, tag_id: listenHarder.id })
end
